/**
 * The different types of {@link Token}s.
 */
export enum TokenType
{
    Whitespace = "Whitespace",
    CarriageReturn = "CarriageReturn",
    NewLine = "NewLine",
    Letters = "Letters",
    Digits = "Digits",
    Period = "Period",
    Comma = "Comma",
    Colon = "Colon",
    Semicolon = "Semicolon",
    ExclamationPoint = "ExclamationPoint",
    QuestionMark = "QuestionMark",
    LeftCurlyBracket = "LeftCurlyBracket",
    RightCurlyBracket = "RightCurlyBracket",
    LeftSquareBrace = "LeftSquareBrace",
    RightSquareBrace = "RightSquareBrace",
    LeftParenthesis = "LeftParenthesis",
    RightParenthesis = "RightParenthesis",
    Hyphen = "Hyphen",
    Underscore = "Underscore",
    EqualsSign = "EqualsSign",
    PlusSign = "PlusSign",
    Asterisk = "Asterisk",
    PercentSign = "PercentSign",
    Ampersand = "Ampersand",
    PoundSign = "PoundSign",
    Backslash = "Backslash",
    ForwardSlash = "ForwardSlash",
    LeftAngleBracket = "LeftAngleBracket",
    RightAngleBracket = "RightAngleBracket",
    VerticalBar = "VerticalBar",
    DollarSign = "DollarSign",
    Caret = "Caret",
    AtSign = "AtSign",
    Tilde = "Tilde",
    Backtick = "Backtick",
    SingleQuote = "SingleQuote",
    DoubleQuote = "DoubleQuote",
    Unknown = "Unknown",
}